### ISSUE TITLE
Endpoint to validate requests made

### ISSUE THREAD

**Issue by avaly** [alepek/smock#9]
The current behavior of the server is solving a part of the test functionality in a test suite: responding to requests.

However, some test suites might also want to validate that certain requests have been made or have not been made during a test run.

A new endpoint could return the set of requests/responses made during a test run. 

This will require tracking the requests and clearing them via a trigger.

**Comment by alepek** [comment]
While I can see the use for this, I think the feature you're suggesting is beyond a level of complexity and responsibility I want fejk to stay at for now.

If the functionality is critical for you I could see this being represented as an express middleware of its own that could be accompanied by fejk (or other express modules for that matter).
